version: '3'
services:
  siavd-backend:
    image: daggerok/jboss:eap-7.0
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    network_mode: "host"
    volumes:
      - ./jboss-eap-deploy/war:/home/jboss-eap-7.0/jboss-eap-7.0/standalone/deployments
      - ./jboss-eap-deploy/config:/home/jboss-eap-7.0/jboss-eap-7.0/configuration:rw
    user: "root"
    command: ./mvnw clean install
    container_name: siavd-api
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  postgres1:
    image: postgres:9.4
    ports:
      - "5432:5432"
    network_mode: "host"
    environment:
      - POSTGRES_USER=db1
      - POSTGRES_PASSWORD=db1
      - POSTGRES_DB=db1
    container_name: db1
    command: postgres -c log_statement=all
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  postgres2:
    image: postgres:9.4
    ports:
      - "5431:5431"
    network_mode: "host"
    environment:
      - POSTGRES_USER=db2
      - POSTGRES_PASSWORD=db2
      - POSTGRES_DB=db2
    container_name: db2
    command: postgres -c log_statement=all
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
